### ISSUE TITLE
Request: A pitch black version

### ISSUE THREAD

**Issue by nanna7077** [vinceliuice/Graphite-gtk-theme#1]
Hi! I just installed this and I already love it!
It would be nice if there is a full black variant or an option to generate one like in the Orchis theme (I was using that till now :) )
Once again, thanks for the awesome theme!

**Comment by vinceliuice** [comment]
No problem!

**Comment by nanna7077** [comment]
Thank you!

**Comment by vinceliuice** [comment]
Added
