### ISSUE TITLE
Artifacts when resizing in gnome 44.

### ISSUE THREAD

**Issue by Aspromayros** [vinceliuice/Graphite-gtk-theme#100]
Artifacts when resizing discord, gimp, blender etc. 

![Screenshot from 2023-04-07 19-17-41](https://user-images.githubusercontent.com/50244573/230642361-d40a321b-8a9c-4ecb-927f-6f63f6430346.png)
![Screenshot from 2023-04-07 19-18-30](https://user-images.githubusercontent.com/50244573/230642453-792ca5ef-34f1-4271-ac28-df0a78511acc.png)

**Comment by vinceliuice** [comment]
Seeks like display card driver issue

**Comment by Aspromayros** [comment]
> Seeks like display card driver issue

It happens only with graphite theme.

**Comment by JerryPenguin** [comment]
I have the same issue with different graphic cards and drivers.
GNOME 44 under Fedora 38

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by Aspromayros** [comment]
> Fixed now!

Works like a charm, thanks!
