### ISSUE TITLE
Quick settings menu broken after update to Gnome 44

### ISSUE THREAD

**Issue by exedotexe** [vinceliuice/Graphite-gtk-theme#104]
![Bildschirmfoto vom 2023-04-24 16-46-04](https://user-images.githubusercontent.com/131688404/234033652-9fd38380-f29d-4dd5-b4a3-dd776fae84a3.png)

Reapplying of the theme didn't worked for me. 
Fedora 38 Workstation.

**Comment by vinceliuice** [comment]
Download the last update on github, this is fixed already
