### ISSUE TITLE
Font Color in QuickPanel Menus

### ISSUE THREAD

**Issue by PapierFliegr** [vinceliuice/Graphite-gtk-theme#107]
Hello, 

first of all I want to say, that I like this theme very much. Tried Orchis first, but this is way better.

Nonetheless I noticed one minor issue.
I installed the theme with 
`./install.sh -c dark -l --tweaks nord rimless normal darker`
and made these changes in gnome-tweaks
![gnome-tweaks](https://github.com/vinceliuice/Graphite-gtk-theme/assets/96027888/ae8152b4-8c25-4719-8110-1dd709143a08)

I then noticed that the font color in the quicksettings for the dropdown menus is too dark to see. As an example:
![font color](https://github.com/vinceliuice/Graphite-gtk-theme/assets/96027888/32190daa-b0ce-4812-abca-396cbfa9af0f)

Is it possible to set the font color to grey/white or whatever the accentcolor is?
i.e. the color of the dropdown elements

### Specs
OS: Fedora 38
DE: Gnome 44

**Comment by vinceliuice** [comment]
Try the last update

**Comment by d1hasib** [comment]
![Screenshot from 2024-03-17 18-18-10](https://github.com/vinceliuice/Graphite-gtk-theme/assets/38419114/841563b6-51dd-4d8c-aa54-cecee5ef8dfa)

I am facing similar issue.
It was fine before switching distro. Now I can not get it work.
