### ISSUE TITLE
--tweak normal ain't working.

### ISSUE THREAD

**Issue by SsubezZ** [vinceliuice/Graphite-gtk-theme#117]
I used normal tweak with dark color but the nautilus sidebar and settings sidebar is still light on Gnome 45. 
![image](https://github.com/vinceliuice/Graphite-gtk-theme/assets/119054422/f29e9549-1b84-42e7-89d6-8478e4002fd3)

**Comment by vinceliuice** [comment]
Fixed

**Comment by SsubezZ** [comment]
New issue now
![Screenshot from 2023-10-17 18-16-33](https://github.com/vinceliuice/Graphite-gtk-theme/assets/119054422/7735a1d7-2dfb-4068-9184-08c23d714253)

**Comment by vinceliuice** [comment]
Now it's ok
