### ISSUE TITLE
[Grub-theme] Selecting icon manually

### ISSUE THREAD

**Issue by CrazyWolf13** [vinceliuice/Graphite-gtk-theme#120]
Hi 
I installed your beautiful grub theme, but how can I set a icon manually for a entry?

I have a reboot entry where I would love to apply them reboot icon from your collection, or a bios button where I would love to apply the efi icon, how do I do this?

**Comment by coffandro** [comment]
https://github.com/vinceliuice/Graphite-gtk-theme/tree/main/other/grub2/assets/logos/1080p is where the icons are located but I sadly think it would be required to more or less create your own version of the Grub config file or something to do this

**Comment by CrazyWolf13** [comment]
Was able to change it by renaming the images, Thanks
