### ISSUE TITLE
Install option -l not working anymore on newer GNOME (45.2)

### ISSUE THREAD

**Issue by UnknownHiker** [vinceliuice/Graphite-gtk-theme#124]
It seems with newer versions of GNOME the -l Option doesnt help anmore to fully apply the theme.
This is what it looks like after running `./install.sh -c dark -l --tweaks nord darker`

![Bildschirmfoto vom 2023-12-30 15-00-49](https://github.com/vinceliuice/Graphite-gtk-theme/assets/98213466/3632c052-5ffc-480a-be7c-b8ed40b4047e)

Is there any workaround for this?

**Comment by vinceliuice** [comment]
Download the last version and try again

**Comment by UnknownHiker** [comment]
Looking good, thanks for this quick fix :)
![Bildschirmfoto vom 2023-12-31 12-32-22](https://github.com/vinceliuice/Graphite-gtk-theme/assets/98213466/e87c05f9-dec8-43af-8205-e6df0a4a299f)
