### ISSUE TITLE
./install.sh not running

### ISSUE THREAD

**Issue by lily-ginger** [vinceliuice/Graphite-gtk-theme#127]
On Ubuntu 22.04 after running ./install.sh (even with sudo) the terminal responds with either "Permission denied" or "command not found".
Not sure if I did something wrong in the installation or if there is a legitimate issue, but I thought I'd leave the issue here in case more people go through the same.

**Comment by wil-m** [comment]
How did you downloaded code? With git clone command? If yes, it should work. Anyway, chmod +x install.sh will fix the issue

**Comment by lily-ginger** [comment]
> How did you downloaded code? With git clone command? If yes, it should work. Anyway, chmod +x install.sh will fix the issue

Tried that way and it still responded with "No such file or directory" :/ 
I downloaded the code as a .zip and extracted it into the home directory, could it be something to do with that? (Sorry for the lack of experience!)

**Comment by lily-ginger** [comment]
Figured out I just didn't have the directory selected in the terminal (for future linux beginners, you have to cd to the directory the folder is in!)
