### ISSUE TITLE
Color of java program should be adjusted when in dart

### ISSUE THREAD

**Issue by starsareintherose** [vinceliuice/Graphite-gtk-theme#13]
![image](https://user-images.githubusercontent.com/37733075/143968218-8f24073d-13e0-43a8-9f30-3f2090444399.png)
Program: Figtree https://github.com/rambaut/figtree/releases

**Comment by vinceliuice** [comment]
Not gtk app do not use gtk theme

**Comment by starsareintherose** [comment]
But it auto fit in gtk, I have no choice.

**Comment by brendanw36** [comment]
Yeah this is an issue with part of the GUI being Java AWT and part being GTK.  FigTree has no GTK code, but the AWT library it uses has GTK code.  I found this [guide](https://askubuntu.com/questions/78088/can-i-apply-a-different-gtk3-theme-from-the-main-one-to-an-individual-applicatio) on how to change the theme used on an individual app level.  I recommend using this guide to set the theme for this app to the default GNOME theme (Adwaita).

**Comment by starsareintherose** [comment]
Thanks, it works
