### ISSUE TITLE
Shadow issue in Gnome 46

### ISSUE THREAD

**Issue by crispywaffles666** [vinceliuice/Graphite-gtk-theme#134]
There are some issues with shadows since updating to Gnome 46: 

![Screenshot from 2024-03-27 21-36-02](https://github.com/vinceliuice/Graphite-gtk-theme/assets/81708706/a29e8f12-1476-426c-bc4a-c110270fb857)

![Screenshot from 2024-03-27 21-34-45](https://github.com/vinceliuice/Graphite-gtk-theme/assets/81708706/d0b07724-b1c7-4177-ae4a-083e313a1b08)

![Screenshot from 2024-03-27 21-29-34](https://github.com/vinceliuice/Graphite-gtk-theme/assets/81708706/d74d004e-0849-4400-af02-01abca88b87a)

installed by cloning the repo and running:

`./install.sh -l -c dark -t teal --tweaks nord rimless normal`

**Comment by rudrab** [comment]
i second this problem

**Comment by crispywaffles666** [comment]
i am not sure how to properly fix, but for now, blur my shell hides the problem in the dock at least.

**Comment by crispywaffles666** [comment]
Fixed in `d5e372f`

Thanks Vince!
