### ISSUE TITLE
Uninstall Option is not Thorough

### ISSUE THREAD

**Issue by SomeUserNameReally** [vinceliuice/Graphite-gtk-theme#136]
Doing `sudo ./install.sh -u` does not bring back GNOME to the state it was in before. I installed with

```sh
sudo ./install.sh -n Graphite -t yellow -c light -g --tweaks colorful rimless
```

on GONME 46.

The colors are still there and the icon sizes for some elements have also changed.

**Comment by vinceliuice** [comment]
run: `sudo ./install.sh -u`

**Comment by SomeUserNameReally** [comment]
> run: `sudo ./install.sh -u`

Ah, how could I have missed it.

**Comment by SomeUserNameReally** [comment]
> run: `sudo ./install.sh -u`

This doesn't work

**Comment by unlux** [comment]
facing the same problem

**Comment by prithvirajkshatriya** [comment]
Run them in this order.

`./install.sh -u -l`
`sudo ./install.sh -u -g`
`sudo ./install.sh -u`
`sudo ./install.sh -g -r`

**Comment by unlux** [comment]
@prithvirajkshatriya thanks.
