### ISSUE TITLE
color of polari should be chagned in standard or light mod

### ISSUE THREAD

**Issue by starsareintherose** [vinceliuice/Graphite-gtk-theme#14]
![image](https://user-images.githubusercontent.com/37733075/143968408-a0f52fd3-589a-4ff5-8145-f93fa72b92f3.png)
![image](https://user-images.githubusercontent.com/37733075/143968427-321c4164-c2c9-4b79-b8f6-7307cd160dae.png)
![image](https://user-images.githubusercontent.com/37733075/143968450-9f20d6ae-9bc6-408a-bbd9-83bfc6c03cca.png)
 Program: Polari https://wiki.gnome.org/Apps/Polari

**Comment by brendanw36** [comment]
I googled around a bit and it looks like the issue here is that Polari now uses GTK 4, and if you're an Arch Linux user, I assume that you're using the new GTK 4 version of Polari.  This theme will have to add support for GTK 4 before Polari will look different.
