### ISSUE TITLE
GTK thumbnails are always blue

### ISSUE THREAD

**Issue by Dejweed** [vinceliuice/Graphite-gtk-theme#140]
No matter the accent color, thumbnail shows blue buttons. Probably install script issue. Screenshot from Cinnamon:
![image](https://github.com/vinceliuice/Graphite-gtk-theme/assets/65261588/c4c9f8f3-81d9-4503-9573-cc6f2c33bd00)

**Comment by Leniwcowaty** [comment]
Hey @vinceliuice ! 
I think this may be related - I just git pulled master branch, tried to re-apply blue theme, and I get the error, that Dark Blue thumbnail wasn't found. Every other color works. Command I use:

`./install.sh -t blue -c dark -s compact -l --tweaks normal --tweaks rimless`

Error I get:

`cp: nie można wykonać stat na '/home/kacper/.gits/Graphite-gtk-theme/src/assets/gtk/thumbnail-blue-Dark.png': Nie ma takiego pliku ani katalogu` (no such file or directory)`

Can you look into this?

**Comment by vinceliuice** [comment]
Now it's ok

**Comment by Leniwcowaty** [comment]
Sorry - another spelling mistake - `thumbnail-bue-Dark.png` instead of `thumbnail-blue-Dark.png` :)

**Comment by vinceliuice** [comment]
ok
