### ISSUE TITLE
Gnome 46/Fedora 40 visual bug in calendar in the notification center

### ISSUE THREAD

**Issue by mediocretwo** [vinceliuice/Graphite-gtk-theme#141]
Hi, I'm using Graphite orange GTK Theme in Gnome 46 with Fedora 40. The Calendar in the notification center is really bugged with the theme, instead of the dates having grey circles with the current date having the theme colour, the dates all have ugly black circles. Attaching screenshot. Please let me know if there is a fix.

![Screenshot from 2024-04-25 16-47-45](https://github.com/vinceliuice/Graphite-gtk-theme/assets/43803024/7ecc0f3d-ed72-40e9-ab6c-21394e78da86)

**Comment by vinceliuice** [comment]
Download the last update and try again

**Comment by issanym** [comment]
_same issue here_
![Screenshot from 2024-04-26 22-14-47](https://github.com/vinceliuice/Graphite-gtk-theme/assets/138514243/be221f87-40bc-4c76-b184-0743acd18614)
![Screenshot from 2024-04-26 22-15-00](https://github.com/vinceliuice/Graphite-gtk-theme/assets/138514243/455bc243-8cbe-432e-ae33-2145923f6190)

**Comment by mediocretwo** [comment]
Thanks, its fixed.
