### ISSUE TITLE
Wallpaper not visible when using --libadwaita in install script

### ISSUE THREAD

**Issue by Tekudachi** [vinceliuice/Graphite-gtk-theme#146]
![Imagen pegada](https://github.com/vinceliuice/Graphite-gtk-theme/assets/99331743/989e0183-caac-4066-9769-237e66749c82)

In a fully upgraded to latest version (sassc, gtk-murrine-engine and gnome-themes-extra packages installed too) Fedora 40, when using install script with --libadwaita options I get this screen covering my wallpaper, from the GNOME overview doesn't happen. Also I try to copy gtk-4.0 to ~/.config directory manually with the same issue. I used the following command ./install.sh --theme blue --color dark --size compact --tweaks black rimless float normal --libadwaita

**Comment by vinceliuice** [comment]
What desktop icons extension you are using ?

**Comment by Tekudachi** [comment]
> What desktop icons extension you are using ?
I use this gnome extension.
![imagen](https://github.com/vinceliuice/Graphite-gtk-theme/assets/99331743/f553a9c2-5150-49ad-98aa-7b5b5ed85a50)

**Comment by vinceliuice** [comment]
Fixed now
