### ISSUE TITLE
Possible to add option for less color in file manager and shutdown/logoff menu?

### ISSUE THREAD

**Issue by Raubion** [vinceliuice/Graphite-gtk-theme#15]
This is a great new theme that perfectly combines the new gnome 40 look with a rather needed, contemporary, flat design. It really gives a nice and modern feel and since a long time I've switched from Vimix to a new theme, particularly because of the rounded corner look, which is greatly integrated, also when hovering on the dock and clicking in menus like Libreoffice, for example. Really well done!

But would it be possible to add an option for less color in the file manager and when clicking on the shutdown/logoff button? I really like the theme a lot, but a little less colorful would be amazing. Like in the regular settings window, for example, where just the selected item is colored. That would be enough color for me.

**Comment by vinceliuice** [comment]
No problem!

**Comment by Raubion** [comment]
Thank you for implementing the normal tweaks. After closing #22 and #23, this one can also be closed!

**Comment by vinceliuice** [comment]
OK 👌
