### ISSUE TITLE
Strange left panel in Nautilus

### ISSUE THREAD

**Issue by cl1ckname** [vinceliuice/Graphite-gtk-theme#156]
- Command: `./install.sh -l -c dark`
- Distro: Ubuntu 23.10
- Application: GNOME nautilus 45.rc
- Result: on screen

![Screenshot from 2024-08-18 18-54-13](https://github.com/user-attachments/assets/7456c664-c854-450c-ad74-b01e2e87d625)

**Comment by vinceliuice** [comment]
It looks like mixed Orchis theme, delete all files in `~/.config/gtk-4.0/` then run: `./install.sh -l -c dark` again

**Comment by cl1ckname** [comment]
It's better, but the selected element still has a strange outline
![image](https://github.com/user-attachments/assets/24683f6c-6ad0-4481-a989-f0cfde98419f)

**Comment by xQT5-ui** [comment]
try to change /etc/environment like this:
 `GTK_THEME="Theme-name-from_~/.themes"` ["Graphite-teal-Dark-nord" for example]
 This solution works for me always for change theme for native gtk-apps

**Comment by cl1ckname** [comment]
Actually, the problem was that is in my `.profile` file there was a `GTK_THEME=Orchis` line. The panel became normal when I changed the line to `GTK_THEME="Graphite-Dark"`. Thanks!
