### ISSUE TITLE
Light theme only?

### ISSUE THREAD

**Issue by RadioactivePotato** [vinceliuice/Graphite-gtk-theme#159]
Command ran: `sudo ./install.sh -t green --tweaks nord -c dark`

![image](https://github.com/user-attachments/assets/75b81d2a-2b8b-4d69-b3aa-19c0a0cb518a)

![image](https://github.com/user-attachments/assets/31666ea0-6502-49e8-935a-71d7e6639a53)

**Comment by RadioactivePotato** [comment]
Distro: Pop!_OS 22.04 LTS

![image](https://github.com/user-attachments/assets/be0d4a5f-2141-493c-8fa3-3d39ebd783ce)

**Comment by vinceliuice** [comment]
Install this: https://extensions.gnome.org/extension/19/user-themes/
then change shell theme

**Comment by RadioactivePotato** [comment]
Fixed, Thanks
