### ISSUE TITLE
[Just a question] What command should I use to get this theme in GNOME 46?

### ISSUE THREAD

**Issue by AlwaysBorderRadius** [vinceliuice/Graphite-gtk-theme#161]
A year ago I managed to install this theme on GNOME 44, but now that I'm on GNOME 46 I'm trying to install it again, but I forgot and can't find the command. I appreciate any help.
![Captura_ (1)](https://github.com/user-attachments/assets/00768e74-04df-4675-ad7f-7bf0fa835e83)

**Comment by vinceliuice** [comment]
Run `./install.sh -h` to get command info

**Comment by AlwaysBorderRadius** [comment]
I've done that, and I've tried multiple combinations of commands until I've run out of ideas. 
That's why I'm asking here, in case anyone knows.

**Comment by vinceliuice** [comment]
`./install.sh -c standard --tweaks rimless -l`

**Comment by AlwaysBorderRadius** [comment]
nice, I added a `-s compact` and now it's perfect again, thanks
