### ISSUE TITLE
Windows not turning dark

### ISSUE THREAD

**Issue by rromoli** [vinceliuice/Graphite-gtk-theme#163]
All is well except I cannot get the dark window and the light sidebar `./install.sh --tweaks nord -l`

Fedora 40 Gnome 46.5

![Screenshot from 2024-09-24 16-17-35](https://github.com/user-attachments/assets/532b202b-cfd1-4c13-9252-86c5ace0f5c1)

**Comment by vinceliuice** [comment]
`./install.sh --tweaks nord -c dark -l`
