### ISSUE TITLE
Gnome-shell 47: handles in top panel menu are missing rims

### ISSUE THREAD

**Issue by KaffeineKicks** [vinceliuice/Graphite-gtk-theme#171]
With the current version of the theme, all handles in gnome-shell panel (for sound volume, screen brightness etc) are missing their rims, leading to them blending with base color. The problem is present in all theme variants (tested both standard and compact), versions (tested standard, light and dark), tweaks (tested rimmed and rimless) and flavors (tested nord-darker flavor with orange accent alongside default).

Handle rims are only missing for gnome-shell; in gtk4 widgets they are present as designed (see the attached screenshot fragment for illustration).

**Theme version:** current git clone (checked 2024-11-01)
**Distribution:** Debian Testing
**gnome-shell version:** 47.0-3
**sassc version:** 3.6.1+20201027-2+b1

![2024-11-01 22-44-05](https://github.com/user-attachments/assets/d48fb903-ddd7-47d3-9feb-32daa7230af9)

**Comment by vinceliuice** [comment]
Gnome-shell 47 theme slider not support borders anymore, I need change it's style
