### ISSUE TITLE
Removing white border around windows

### ISSUE THREAD

**Issue by telometto** [vinceliuice/Graphite-gtk-theme#18]
I tried looking through the `gtk.css` file to see if I could remove the white border around the windows, but there's _a lot_ of `border`, `border-radius` etc.

Thanks.

**Comment by vinceliuice** [comment]
Why not try `./install.sh --tweaks rimless` ?

**Comment by telometto** [comment]
Ah, my bad. I got it from gnome-look.org

I'm guessing it will extract the contents into `$HOME/.themes`, right? And, should I need to uninstall it, I just delete the folder?

**Comment by vinceliuice** [comment]
Just run the it, it will replace the old one
