### ISSUE TITLE
Bug in the task widget extension

### ISSUE THREAD

**Issue by tippex-ls** [vinceliuice/Graphite-gtk-theme#20]
Hi !
In the Task widget extension, I have an issue with the tick boxes it creates: they appear in two different places in the same line, as the image shows.
I do not see this bug in any other theme. I tried to reinstall the theme, without success. It appears even with only two extensions activated, namely User Themes and Task Widgets.
Thank you !

Config: Fedora 35, Gnome 41, Task Widget v10, last version of Graphite-gtk-theme

![Capture d’écran de 2021-12-20 10-14-09](https://user-images.githubusercontent.com/70751982/146743460-16233562-fafc-4a0e-93ce-4a485bb336ee.png)
.

**Comment by vinceliuice** [comment]
Fixed!

**Comment by tippex-ls** [comment]
Nice ! Works perfectly
