### ISSUE TITLE
Add an option to change side of file manager

### ISSUE THREAD

**Issue by Sowgro** [vinceliuice/Graphite-gtk-theme#22]
There should be an option to make the side of the file manager look more like the side of settings and other apps. 
![image](https://user-images.githubusercontent.com/69283684/147796625-4b37d646-e51c-484b-85c2-fa870970f6d9.png)
![image](https://user-images.githubusercontent.com/69283684/147796671-a1139819-532c-44ea-8c82-adea2d7c5ec1.png)

**Comment by vinceliuice** [comment]
![Screenshot from 2021-12-31 11-36-09](https://user-images.githubusercontent.com/7604295/147801774-92514b74-3377-45d9-9784-139396879d31.png)

**Comment by vinceliuice** [comment]
Run `./install.sh --tweaks rimless normal` to install it

**Comment by Sowgro** [comment]
Thank you!!!

**Comment by vinceliuice** [comment]
You are welcome!
