### ISSUE TITLE
Notifications in "normal" shell theme

### ISSUE THREAD

**Issue by Aman9das** [vinceliuice/Graphite-gtk-theme#23]
When "normal" version of graphite is in use, the shell theme shows sub-menus (suspend, restart, power off) as accented in the notification area.

I think users of "normal" versions would prefer the sub-menu to be in background colour, and just the selected option (power off / log-out) to be accented. Just like nautilus.

What is the consensus on this?

**Comment by brendanw36** [comment]
Some screenshots would be nice.  I don't use GNOME so I would have to create a VM just to see what you're talking about.

**Comment by Aman9das** [comment]
Right now "normal" nautilus looks like: 
![Screenshot from 2022-01-03 07-41-27](https://user-images.githubusercontent.com/39594914/147895673-e0a71b5e-bfbc-4435-b48b-b3fbfe4af0e3.png)

And the notification area looks like:
![Screenshot from 2022-01-03 07-44-52](https://user-images.githubusercontent.com/39594914/147895727-706424a8-6558-4ca9-9380-89ad2c19710e.png)

My suggestion would be to make "normal" notification could look like this:
![Screenshot from 2022-01-03 07-46-18](https://user-images.githubusercontent.com/39594914/147895763-0896a789-7843-4327-b3ba-cb4d92173a5a.png)

Is there agreement that this is what users of "normal" version would want..

**Comment by vinceliuice** [comment]
No problem, I'll update this

**Comment by Raubion** [comment]
I think there would be more design consistency if the bottom corners of the selected submenu were also rounded. So in the attached screenshot the highlighted bar of 'gebalanceerd' in the color 5e81ac with rounded corners at the bottom.

![rounded_corners](https://user-images.githubusercontent.com/35173208/147969552-902cc1f8-4353-4937-b5ee-d096ad8d3f3c.png)
