### ISSUE TITLE
[Request] Darker Nord color scheme for dark theme

### ISSUE THREAD

**Issue by Raubion** [vinceliuice/Graphite-gtk-theme#24]
Currently, the graphite dark nord variant is not very dark. At #434c5e it's quite light and blue. Any chance you could make it more dark? Maybe like two shades darker from [the polar night pallete,](https://www.nordtheme.com/docs/colors-and-palettes) at #2e3440?

**Comment by vinceliuice** [comment]
No problem, I'll uodate this

**Comment by Raubion** [comment]
Amazing! Thank you

**Comment by vinceliuice** [comment]
You are welcome!, That looks great!

**Comment by coral-hungus** [comment]
Hi,  I like the new dark nord color, but I also have use for the previous lighter dark version. Is it possible to pick between the two or add an option to do so? Thanks!

**Comment by vinceliuice** [comment]
is the primary color too dark？

**Comment by Raubion** [comment]
I really like the current primary colour and all the different shades. Maybe a nord light and dark theme with the previous and current colour schemes?

**Comment by vinceliuice** [comment]
I can use the previous light colorscheme, because I think the new primary color for the light version is too dark not easy to distinguish it is Nord color

**Comment by Raubion** [comment]
Yeah that sounds like a good option. Now it's mostly white. Light blue #434c5e is a nord colour and was very nice, just too light for my taste.

Really hope you won't change #2e3440 dark primary colour though. Really cool how the dark Nord theme currently looks!

**Comment by vinceliuice** [comment]
Don't worry, dark one I'll keep it, just change the light one

**Comment by coral-hungus** [comment]
Hi, 434c5e is what I'm looking for - sorry I wasn't specific. Thanks!

**Comment by coral-hungus** [comment]
And I agree, the new color for dark mode is good. Maybe the 434c5e would be good for a “medium dark” or “frost” mode?

**Comment by Raubion** [comment]
What are your thoughts on changing the dividing lines to a darker instead of a lighter color? See attached mockup of the settings app.

![dark-divider-mockup](https://user-images.githubusercontent.com/35173208/148684049-97852f2b-84f5-407b-ac86-05f1069c0bea.png)
.
