### ISSUE TITLE
Checkboxes are the same colors as the theme color. 

### ISSUE THREAD

**Issue by g-a-b-r-i-e-l** [vinceliuice/Graphite-gtk-theme#28]
So I discovered this when I tried to shut down the sistem and asked me if I want to update it, there was a checkbox that when I clicked it looked like nothing changed. Can you make it a little darker to see it and make it change colors when it is clicked?

**Comment by vinceliuice** [comment]
Is it a checkbox on gnome-shell dialog?

**Comment by g-a-b-r-i-e-l** [comment]
![Screenshot from 2022-01-08 15-28-57](https://user-images.githubusercontent.com/81432211/148645997-5f27beb4-019f-40cc-b557-e1c29066c763.png)
> Is it a checkbox on gnome-shell dialog?

![Screenshot from 2022-01-08 15-28-22](https://user-images.githubusercontent.com/81432211/148646003-8df8214a-b30e-491c-9eaa-88b59390dc28.png)
