### ISSUE TITLE
Unaesthetic issues on Firefox with Graphite light theme

### ISSUE THREAD

**Issue by Nicryc** [vinceliuice/Graphite-gtk-theme#29]
There are two unaesthetic things on Firefox using the Graphite light theme:

- There is a thick grey line separating the tabs area from the tool bar
- There is little semi-transparent triangles in the upper rounded corners of the window

See screenshot below.

![firefox-graphite-theme](https://user-images.githubusercontent.com/15157120/148650664-90effa8f-cce9-48af-9016-7da9f759d09c.png)

OS: Fedora 35
DE: Gnome 41.2
Graphite theme: Light
Graphite version: 78e5421

**Comment by vinceliuice** [comment]
Not a theme issue, it's firefox issue  https://bugzilla.mozilla.org/show_bug.cgi?id=1408360

**Comment by Nicryc** [comment]
OK no problem, I wasn't entirely sure if it was a theme or a Firefox issue. What about the grey line?

**Comment by vinceliuice** [comment]
Firefox set this line, not gtk theme

**Comment by Nicryc** [comment]
Ok my bad.

**Comment by Raubion** [comment]
You might be able to change this with https://color.firefox.com/
