### ISSUE TITLE
Top panel colour still default on Pop_OS! 21.10

### ISSUE THREAD

**Issue by xQzca** [vinceliuice/Graphite-gtk-theme#30]
Hi, when I use this theme (more specifically, the nord, rimless and normal version) the top panel still stays the default brownish colour of Pop_OS!, if there is a way to fix this please let me know, thanks.

![image](https://user-images.githubusercontent.com/87734338/148744455-748f6052-1c6f-4e2d-8bf5-d58fcb104e7d.png)

**Comment by Raubion** [comment]
I haven't used POP_OS! but if it's like regular gnome, have you also changed the theme of gnome shell? See also #31

**Comment by Yush08** [comment]
Install the User themes extension.
Go to Gnome-tweaks.
Select "Graphite-dark" in the "shell" field in the "Appereance" section.

Regards - Yush.

**Comment by xQzca** [comment]
fixed, thanks yush :)
