### ISSUE TITLE
Question: Top bar theme doesn't change

### ISSUE THREAD

**Issue by RickStanley** [vinceliuice/Graphite-gtk-theme#31]
Hello, thank you for this beautiful theme!

I'm trying to understand why isn't the top bar changing along with the rest of the UI:

![grafik](https://user-images.githubusercontent.com/23178554/149260342-b39cabf0-d7ec-483f-a5e6-d15a6639c4a2.png)

I cloned the project and ran ./install.sh

**Comment by RickStanley** [comment]
Nevermind, found out I had to install the shell.

**Comment by pedrohba1** [comment]
What do you mean by installing the Shell? I'm kinda new to GTK theming, what did you have to do to enable the Graphite topbar?

**Comment by vinceliuice** [comment]
@pedrohba1  Install `gnome-shell-extensions` then open `gnome-extensions-app`  enable `User Themes`, last install `gnome-tweaks` to change shell theme
