### ISSUE TITLE
Error in grub theme install script

### ISSUE THREAD

**Issue by romildo** [vinceliuice/Graphite-gtk-theme#35]
https://github.com/vinceliuice/Graphite-gtk-theme/blob/1bb264824787f3f99ecd6821cbfc3f210b0f3a16/other/grub2/install.sh#L369

The last line should be
```bash
 exit 1
```

**Comment by romildo** [comment]
Probably the script should not fail at the end.

**Comment by vinceliuice** [comment]
You are right it should be `exit 0` now
