### ISSUE TITLE
Grub theme installation

### ISSUE THREAD

**Issue by romildo** [vinceliuice/Graphite-gtk-theme#36]
I want to add the possibility to install the grub theme in [the package `graphite-gtk-theme` for NixOS](https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/themes/graphite/default.nix), but the provided script is not suitable, as it tries to edit the configuration file. In [NixOS](https://nixos.org/) the grub configuration is done differently.

Can the `install.sh` script be refactored so that it becomes possible to just copy the theme files to the destination directory, without trying to modify the system grub setup? And without imposing root access.

Also with an option to choose the destination directory.

**Comment by vinceliuice** [comment]
If not modify the grub config file, grub will not use the theme installed

**Comment by romildo** [comment]
NixOS uses a central configuration file written in the Nix language, where we can have the complete configuration of a machine. The grub theme is set in this file.

For instance, in my notebook configuration file there is something like
```nix
    grub = {
      enable = true;
      default = "saved";
      devices = [ "nodev" ]; # ?
      efiSupport = true;
      fsIdentifier = "label"; # identify devices by label
      useOSProber = true; # append entries for other OSs
      #gfxmodeEfi = "1024x768x32,auto";
      font = "${pkgs.jetbrains-mono}/share/fonts/truetype/JetBrainsMono-Regular.ttf";
      fontSize = 20;
      theme = "${pkgs.graphite-gtk-theme}/grub/themes/Graphite";
      extraEntries = ''
        menuentry "Reboot" {
          reboot
        }
        menuentry "Power off" {
          halt
        }
      '';
    };
```

**Comment by vinceliuice** [comment]
Maybe make another script file for nixos,  and keep this install.sh still for other linux
