### ISSUE TITLE
[Request] Add a theme version without any borders

### ISSUE THREAD

**Issue by aScordino** [vinceliuice/Graphite-gtk-theme#4]
Hello **vinceliuice**! 
First of all, thank you for this amazing theme. I was searching for a pure dark theme like Vimix's theme, but _more modern_.
I got a request for this: could you make please a version without the borders? Nothing wrong, I just don't like them.
You could call it "NoBorder or Bordless".
TYSM!

**Comment by Trikenstein** [comment]
+1 for this idea. The thick border is not very nice. If it was only on the window in focus, it would be still be bearable. But that thick border appears on every windows. Please note that GTK2 apps doesn't have that thick border and they do indeed look better.

While you are at it, maybe reduce the roundness of the round corner as well? That round corner is also inconsistent. Sometimes 4 round corners on GTK3 apps, sometimes 2 corners (GTK2 apps, Gnome Terminal, Gedit).

**Comment by vinceliuice** [comment]
No problem!
