### ISSUE TITLE
Color schemes for GTK2 are incomplete

### ISSUE THREAD

**Issue by mseveritt** [vinceliuice/Graphite-gtk-theme#43]
Dear Vince, first a big thank you for your beautiful themes.
For Graphite, I really like the combination of color teal with nord and darker. 
Unfortunately, this is not completely reflected in the GTK2-theme:
1. If the install-script is run with -c teal, the GTK2-theme becomes blue.
2. The nord colors are not respected in the GTK2-theme.

Is it possible to include this such that GTK2 and GTK3 themes are in sync?
Thanks in advance.

**Comment by vinceliuice** [comment]
Ok, I'll fix this!

**Comment by vinceliuice** [comment]
Fixed !
