### ISSUE TITLE
[Request] Add a GDM version of the theme

### ISSUE THREAD

**Issue by aScordino** [vinceliuice/Graphite-gtk-theme#5]
Hello... again!
I am back since I got another request for you. I saw none of your themes got this feature but it may be cool to implement this.
Why don't you make a GDM3 theme? It would just make your themes matching perfectly and look good :-D
Have a nice day,
Antonino

**Comment by vinceliuice** [comment]
I personally not recommend users to use GDM theme, because mistakes will cause the system fail  to login.

**Comment by aScordino** [comment]
Okay, thank you for clarifying :( 
But it makes sense. Have a good day.
