### ISSUE TITLE
Theme doesn't apply to various elements

### ISSUE THREAD

**Issue by Ileca** [vinceliuice/Graphite-gtk-theme#54]
Contrary to what I can see on your screenshots, the theme doesn't apply to my Gnome shell properly. It doesn't apply to the status bar itself, the status bar's various menus (such as menus for the app indicators), and the contextual menu on the desktop.

It also applies partially to Qt apps' window decorations. The color and upper round corners are here, but no white border (I use dark nord) and no bottom round corners. Without the white border, all the Qt apps are blending into each other. (I am using your Kvantum theme for the inside btw. ;) )

I am using your screenshots as a comparison but maybe your theme is only for GTK apps (to which it does apply) and not the Gnome shell itself?

Beyond that, beautiful theme. No problem with GTK apps themselves.

I am new to this. If I did something wrong, I hope you can help me. Thanks!

Ubuntu 21.10
Gnome 40.4.0
Wayland

**Comment by vinceliuice** [comment]
Do you know how to change the gnome-shell theme? and Qt apps not support bottom radius

**Comment by vinceliuice** [comment]
Maybe you need google how to change gnome-shell theme first

**Comment by Ileca** [comment]
Aouch, I have made a fool of myself. I thought "shell" in Tweaks was related somehow to the unix shell (bash, etc.) and like it was disabled, I thought it was something very specific that nobody uses.
I now have applied your theme to "shell".

I have rebooted but the Qt apps still don't have a white border. Is it something impossible or did I miss something, again?

**Comment by vinceliuice** [comment]
I removed the border for app like qt for some reason

**Comment by Ileca** [comment]
By "some reason", do you mean it was intentional or that it was accidental and you intend to fix it?

**Comment by Ileca** [comment]
Closing the issue because it was fixed in the meantime.
