### ISSUE TITLE
Question about Grub theme installation

### ISSUE THREAD

**Issue by Nakamerica** [vinceliuice/Graphite-gtk-theme#57]
Hi, how exactly do i install the grub theme? Not able to figure out which repo to clone, etc.

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/Graphite-gtk-theme/tree/main/other/grub2

**Comment by Nakamerica** [comment]
Thank you so much.

**Comment by Nakamerica** [comment]
I tried it right now but I'm getting the following error:

`fatal: repository 'https://github.com/vinceliuice/Graphite-gtk-theme/tree/main/other/grub2/' not found
`

**Comment by vinceliuice** [comment]
Just download the gtk theme repo and goto ～/main/other/grub2  then run the install.sh
