### ISSUE TITLE
[Request] Graphite theme for KDE

### ISSUE THREAD

**Issue by lunw1024** [vinceliuice/Graphite-gtk-theme#6]
Hi, thanks for the awesome theme!
Do you have any plan for a KDE version for this theme?

**Comment by vinceliuice** [comment]
Yes, I'm making it now

**Comment by THEGODFATHERRX** [comment]
I really love this theme, if there was a KDE/QT version for this, that what be AWESOME!!!

**Comment by lunw1024** [comment]
@vinceliuice any updates on that?

**Comment by vinceliuice** [comment]
Finished: https://github.com/vinceliuice/Graphite-kde-theme
