### ISSUE TITLE
All color variants are Purple.

### ISSUE THREAD

**Issue by Zetta1Reid0** [vinceliuice/Graphite-gtk-theme#61]
Distro : Arch
Theme version : Git master branch.
Somehow color variants don't work.
Doesn't matter what color i put after -t, --theme on install script ,every time the color is Purple.
I tried Arch Aur git theme package and manual install:sudo ./install.sh -t all -s compact --tweaks nord darker

![Снимка на екрана на 2022-05-01 09-29-34](https://user-images.githubusercontent.com/79805086/166134960-431ed031-84e9-4778-9077-428fe00da175.png)
.

**Comment by ArjunSindhya** [comment]
Having the same issue.

**Comment by Akeeru** [comment]
I fixed the color bug

**Comment by Zetta1Reid0** [comment]
Will test it when I can.

**Comment by Zetta1Reid0** [comment]
It works correctly now. Closing the issue.
