### ISSUE TITLE
Chromium 101.0.4951.41 displays a transparent 1 pixel bar at the top

### ISSUE THREAD

**Issue by sug0** [vinceliuice/Graphite-gtk-theme#62]
Cross referencing the following issue: https://github.com/void-linux/void-packages/issues/36980

The Graphite version I am using is 09fb152df42c4294595f39a9a61d4827a6381709. Here is what it looks like with Chromium:

![](https://pomf2.lain.la/f/820cbr.png)

**Comment by sturlabragason-devoteam** [comment]
I also have exactly this same issue in the Graphite derivative [Catppuccin Mocha.](https://github.com/catppuccin/gtk). 

Affects both Chrome and Brave browser.

**Comment by sug0** [comment]
I haven't had this issue for a while. I built the latest version of the theme in `main`.

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by sturlabragason-devoteam** [comment]
Thanks. Feel free to close since I've found the relevant discussion for me over in [https://github.com/catppuccin/gtk/issues/35](https://github.com/catppuccin/gtk/issues/35)
