### ISSUE TITLE
Gnome 42 Applications Bug

### ISSUE THREAD

**Issue by OptixWolf** [vinceliuice/Graphite-gtk-theme#66]
Gnome 42 Applications have Standard Theme when Graphite is applied

**Comment by Raubion** [comment]
This is not a Graphite bug, but a consequence of the implementation of libadwaita. For now, you can copy the gtk.css to /.config/gtk-4.0, but bugs will remain, although it will be closer. See also my issue about this: #63 

For more information about libadwaita: https://news.itsfoss.com/gnome-libadwaita-library/
