### ISSUE TITLE
Firefox Corner Issue

### ISSUE THREAD

**Issue by OptixWolf** [vinceliuice/Graphite-gtk-theme#74]
Firefox has weird corners

![Bildschirmfoto vom 2022-08-08 00-00-58](https://user-images.githubusercontent.com/62619140/183312704-800cad29-892d-4eac-b346-a5f726eef14b.png)

**Comment by athamour1** [comment]
I fixed it a little unorthodox with this [exension](https://extensions.gnome.org/extension/5237/rounded-window-corners/), and it also rounds every bottom edge
![image](https://user-images.githubusercontent.com/39333862/187645600-ea0a1c6b-aced-49e4-a0a5-616a2b0fe134.png)
![image](https://user-images.githubusercontent.com/39333862/187645669-e27c6b10-bc5b-4088-8368-036fc6801a9e.png)

**Comment by OptixWolf** [comment]
Thanks, I will test this later
