### ISSUE TITLE
The Grub theme doesn't work on Fedora 36

### ISSUE THREAD

**Issue by Or4ma** [vinceliuice/Graphite-gtk-theme#76]
it shows me this error what ever i do, i tried all the ways on the internet but nothing has worked
![image](https://user-images.githubusercontent.com/110340616/187422790-cbbc9b8d-bfce-4c2a-b2ab-50cdddde148a.png)

**Comment by vinceliuice** [comment]
No such device ... , you must lost your disk partition

**Comment by fredericpetit02** [comment]
> it shows me this error what ever i do, i tried all the ways on the internet but nothing has worked ![image](https://user-images.githubusercontent.com/110340616/187422790-cbbc9b8d-bfce-4c2a-b2ab-50cdddde148a.png)

change default directory for store themes into `/boot/grub(2)/themes`
