### ISSUE TITLE
Graphite-red-Dark-nord theme not applying to Nautilus.

### ISSUE THREAD

**Issue by Kushagra-Srivastava** [vinceliuice/Graphite-gtk-theme#79]
The theme does not apply to nautilus file manager, it remains same as before.
![image](https://user-images.githubusercontent.com/84167616/194799170-6d2daa4c-fcc2-4c88-9572-0c9d4ac526ae.png)

**Comment by vinceliuice** [comment]
Ubuntu? snap app not supported

**Comment by Kushagra-Srivastava** [comment]
> Ubuntu? snap app not supported

hmm so nautilus is a snap? shoots.

**Comment by Kushagra-Srivastava** [comment]
hmm when i run `snap list` it gives the following output:

`
Name                         Version           Rev    Tracking         Publisher   Notes
bare                             1.0               5              latest/stable    canonical✓  base
core20                      20220826          1623     latest/stable    canonical✓  base
gnome-3-38-2004    0+git.6f39565     119       latest/stable/…  canonical✓  -
gtk-common-themes 0.1-81-g442e511   1535   latest/stable/…  canonical✓  -
snap-store                 41.3-64-g512c0ff  599    latest/stable/…  canonical✓  -
snapd                      2.57.2            17029  latest/stable    canonical✓  snapd
snapd-desktop-integration  0.1               14     latest/stable/…  canonical✓  -

`
can't see nautilus installed as snap. By the way, the theme also doesn't work in settings application.

**Comment by vinceliuice** [comment]
Then it should be libadwaita app, run `./install.sh -l`

**Comment by Kushagra-Srivastava** [comment]
I tried with the command `./install.sh -l -t orange --tweaks nord rimless`
But still the apps don't change. Nautilus is version 42.2

**Comment by vinceliuice** [comment]
What's your ubuntu version?

**Comment by Kushagra-Srivastava** [comment]
Ubuntu 22.04 LTS

**Comment by Kushagra-Srivastava** [comment]
Still doesn't work after [this](https://github.com/vinceliuice/Graphite-gtk-theme/commit/31451e3fcbe504e73c5e592a1768be1079f22219) commit.

**Comment by Kushagra-Srivastava** [comment]
[UPDATE]

WORKS AFTER UPDATE TO (kinetic Kudu) 22.10 Non-LTS release.
