### ISSUE TITLE
Theme is broken with libadwaita-1.2.0 and nautilus-43

### ISSUE THREAD

**Issue by KaffeineKicks** [vinceliuice/Graphite-gtk-theme#80]
Problem:
Linking the theme with current libadwaita (setting _--libadwaita_ option during installation) breaks decorations in Nautilus.

Description:
Header string is rendered in the same white (both text and decorations), side panel is rendered incorrectly. Switching to dark mode only changes the main panel background, leaving font color black. In addition, dark mode is applied only in the grid view but not in the list view.

Examples:
Nautilus Grid view, Light mode:

![2022-10-13 13-18-20](https://user-images.githubusercontent.com/115702388/195573870-3c995d30-aa3b-4a0e-aceb-b60108b7d76c.png)

Nautilus Grid view, Dark mode:
![2022-10-13 13-18-28](https://user-images.githubusercontent.com/115702388/195573926-3068743a-51da-49e0-827c-3e54db46163e.png)

Nautilus List view, Dark mode:
![2022-10-13 13-18-51](https://user-images.githubusercontent.com/115702388/195573979-b93fa574-6d75-48a1-a836-4cb15dc43615.png)

Graphite GtK theme version: 2022-09-02
libadwaita-1-0 version: 1.2.0-1
nautilus version: 43.0-1
Distro: Debian bookworm/sid

Additional remarks:
Theme bundled at Gnome-Look.org is versioned 2022-09-25, marked as "fixed problems with libadwaita"; despite that, the problem still persists with bundled v2022-09-25 package.

Might be connected to issue https://github.com/vinceliuice/Graphite-gtk-theme/issues/79

**Comment by vinceliuice** [comment]
Fixed now! if you want to use the dark theme for libadwaita, you need to run: `./install.sh -c dark -l`
