### ISSUE TITLE
Transparent Backgrounds in GNUCash Dropdowns

### ISSUE THREAD

**Issue by ardichoke** [vinceliuice/Graphite-gtk-theme#83]
When using the graphite theme, dropdowns in GNUCash have transparent backgrounds making them nearly unreadable. I've seen this issue before with other themes, here's a sample fix for it: https://github.com/pop-os/gtk-theme/pull/470

**Comment by ardichoke** [comment]
I pulled in the latest changes, reinstalled the theme and reapplied it, unfortunately, it has not fixed the transparency issues. Those drop-downs are still illegible in most cases with this theme applied.

**Comment by vinceliuice** [comment]
I think now it's fixed!
![Screenshot from 2022-11-03 10-57-18](https://user-images.githubusercontent.com/7604295/199639561-9182ea61-806e-4729-a60a-05c26dec90c4.png)

**Comment by ardichoke** [comment]
So, it is partially fixed, as in your screenshot, the dropdown shows up when there aren't any existing transactions under it... however, when you have transactions in the ledger, the dropdown is not readable where it is over top of them. See here: 
![image](https://user-images.githubusercontent.com/112836/199722169-5a691d3d-8aeb-49fa-a95c-b84b45496b51.png)

**Comment by ardichoke** [comment]
Just wanted to give this a bump. Could this issue be reopened at least for future investigation? I can't reopen it.
