### ISSUE TITLE
[Question] Nautilus Sidebar Design for Nemo

### ISSUE THREAD

**Issue by fugo** [vinceliuice/Graphite-gtk-theme#89]
```
Linux Arch   
DE: Budgie  
WM: Mutter(Budgie) 43.1  
Theme: Graphite-blue-Dark  
Nautilus: 43.1
Nemo: 5.6.0
```
Thank you for this beautifull theme, I used a lot of dark themes and yours is now my favorite. :+1:   
I prefer to use Nemo than Nautilus because of its better capabilities/tools.  

**Question:**  
I want the same **sidebar** in Nemo like Nautilus, is this possible?  
The color I changed with the CSS in `~/.config/gtk-3.0`.  
Perhaps you can tell me the code only for the Nautilus sidebar to get the borders etc.  I know the selectors (Class/ID) for Nemo are a bit different.

**Comment by vinceliuice** [comment]
No problem!

**Comment by fugo** [comment]
Thank's a lot  for your update:+1:   
Now Nemo looks great!

![nemo new look](https://i.imgur.com/VUVwYdg.png "Nemo with Graphite & Suru++")
