### ISSUE TITLE
The GDM theme only works with the "default" (white) theme

### ISSUE THREAD

**Issue by mrmeszaros** [vinceliuice/Graphite-gtk-theme#91]
It installs with --theme default, but not with any other option. Here is for example with orange:
```
vagrant@ubuntu2204 ~> sudo Sources/Graphite-gtk-theme/install.sh --color dark --theme orange --tweaks normal --tweaks darker --gdm
GNOME Shell 42.5
Install Normal sidebar version! ...
Install darker version! ...

Install Graphite-orange-Dark GDM Theme...
/home/vagrant/Sources/Graphite-gtk-theme/src/main/gnome-shell/gnome-shell-theme.gresource.xml: Failed to locate “assets/toggle-on-dark.svg” in any source directory.
```

I think I located the issue: the `toggle-on-dark.svg` is present inside `src/assets/gnome-shell/theme` but not in any of the `src/assets/gnome-shell/theme${theme}` directories (where theme is one of the colors).

Line 282 of the install.sh script is copying those SVG files:
https://github.com/vinceliuice/Graphite-gtk-theme/blob/966e98c4ea348f739594f65eae8b824abdb1a1b4/install.sh#L282

I'd gladly fix this, but I am unsure how to fix it (I guess the other SVG files should be generated by some script).

**Comment by vinceliuice** [comment]
Fixed
