### ISSUE TITLE
doesn't completely remove

### ISSUE THREAD

**Issue by ash27kan** [vinceliuice/Graphite-gtk-theme#97]
I removd everything but it still there even when I change the theme.
![Screenshot from 2023-03-07 20-37-42](https://user-images.githubusercontent.com/86627837/223578092-a8dc0c35-bba2-4d0d-baee-887a51eb4f03.png)

**Comment by vinceliuice** [comment]
Uninstall GDM theme

**Comment by vinceliuice** [comment]
`sudo ./install.sh -g -r`

**Comment by ash27kan** [comment]
> `sudo ./install.sh -g -r`
yes it works, thanks.

**Comment by prithvirajkshatriya** [comment]
Run them in this order.

`./install.sh -u -l`
`sudo ./install.sh -u -g`
`sudo ./install.sh -u`
`sudo ./install.sh -g -r`
